### ISSUE TITLE
Error installing `less-rails` through Bundler

### ISSUE THREAD

**Issue by andrewudell** [hackmh/shoutout#62]
![screenshot 2016-07-05 12 26 09](https://cloud.githubusercontent.com/assets/1693065/16663446/f876936e-4430-11e6-8d9d-51558754eddf.png)

**Comment by mattjmcnaughton** [comment]
This seemed to be an error with networking within the Docker container. If it happens again, try restarting the virtual machine running Docker (if you are on Mac or Windows).
